[2024-09-12 21:02:23,769] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-12 21:02:26,948] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-12-1/mb16.json Launching profiler...
[2024-09-12 21:02:28,788] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:02:32,054] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 12, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:02:33,974] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 21:02:35,073] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 21:02:58,522] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 21:03:01,386] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 21:03:01,387] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-12 21:03:06,763] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-12 21:03:11,460] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 21:03:12,027] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 21:03:12,027] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 21:03:12,028] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 21:03:12,028] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 21:03:12,028] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 12 nodes latency
[2024-09-12 21:03:12,253] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 21:03:12,253] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 21:03:13,330] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221', '172.21.0.47:2222', '172.21.0.47:2223']
[2024-09-12 21:03:13,330] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 21:03:15,287] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:03:18,428] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 21:03:18,428] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:03:20,294] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 21:03:21,401] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 12)
min_nodes: 2, max_nodes: 12, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
[2024-09-12 21:03:24,815] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 21:03:24,816] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11]}
[2024-09-12 21:03:24,816] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 12, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11]}
[2024-09-12 21:03:24,817] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 38653
[2024-09-12 21:03:24,817] [INFO] [agent.py:232:forward_worker_port] Received worker port: 38653 from worker. Forwarding it to master...
[2024-09-12 21:03:24,819] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 21:03:24,819] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 38653 from master
[2024-09-12 21:03:25,261] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 21:03:25,261] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-12 21:03:25,261] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 21:03:25,365] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:03:25,592] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:03:25,922] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 21:03:26,689] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:03:28,223] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:03:28,548] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:03:32,785] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 4 x <oobleck.PipelineTemplate.3nodes> pipelines (b: 16)
B: 64
dataloader: mbs 16
[2024-09-12 21:03:45,198] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 21:03:45,199] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.02166152000427246, forward time: 7.330454349517822, backward time: 17.72304368019104
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 0 done
[2024-09-12 21:08:04,049] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 258834.33
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-12 21:08:04,051] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 4.2465 GB | max_mem_allocated: 8.9497 GB | cache_allocated: 11.1289 GB | max_cache_allocated: 11.1289 GB
step: 1
step in try: 1
load_mbs: 0.01682758331298828, forward time: 6.884491682052612, backward time: 17.7176251411438
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 1 done
[2024-09-12 21:13:51,952] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 347888.25
[2024-09-12 21:13:51,954] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 4.2465 GB | max_mem_allocated: 11.0293 GB | cache_allocated: 12.7070 GB | max_cache_allocated: 12.7070 GB
step: 2
step in try: 2
load_mbs: 0.024996519088745117, forward time: 6.88677978515625, backward time: 17.73412251472473
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 2 done
[2024-09-12 21:18:36,497] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 284536.00
[2024-09-12 21:18:36,499] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 4.2465 GB | max_mem_allocated: 11.0293 GB | cache_allocated: 12.7070 GB | max_cache_allocated: 12.7070 GB
step: 3
step in try: 3
load_mbs: 0.021939992904663086, forward time: 6.878703832626343, backward time: 17.719003915786743
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 3 done
