[2024-09-12 22:04:50,638] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 7
[2024-09-12 22:04:54,358] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-8-1/mb16.json Launching profiler...
[2024-09-12 22:04:56,198] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 22:04:59,349] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 7, world_size 8, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 22:05:01,419] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 22:05:02,352] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 22:05:25,906] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 22:05:26,275] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 22:05:26,275] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 22:05:36,825] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 22:05:36,825] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 22:05:36,825] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 22:05:36,826] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 22:05:36,827] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 8 nodes latency
[2024-09-12 22:05:37,015] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 22:05:37,015] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 22:05:38,150] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.46:2223, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223']
[2024-09-12 22:05:38,150] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 22:05:40,034] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 22:05:43,163] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 22:05:43,163] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.46:2223
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 22:05:45,282] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 22:05:46,447] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 8)
min_nodes: 2, max_nodes: 8, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
[2024-09-12 22:05:47,013] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 22:05:47,013] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 36507 from master
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
[2024-09-12 22:05:47,138] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 22:05:47,139] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7]}
[2024-09-12 22:05:47,139] [INFO] [engine.py:739:initialize_distributed] init pg: rank 7, world_size: 8, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7]}
[2024-09-12 22:05:47,139] [INFO] [engine.py:755:initialize_distributed] Waiting for a port information...
[2024-09-12 22:05:47,139] [INFO] [engine.py:758:initialize_distributed] Received torch master: 172.21.0.42:2220.36507
[2024-09-12 22:05:47,253] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 22:05:47,254] [INFO] [engine.py:775:initialize_distributed] [rank: 7] Distributed initialization is done.
[2024-09-12 22:05:47,254] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:47,687] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:47,933] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:48,260] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:48,492] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 22:05:48,585] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 4 x <oobleck.PipelineTemplate.2nodes> pipelines (b: 16)
B: 64
dataloader: mbs 16
[2024-09-12 22:06:04,056] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 22:06:04,057] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.00028133392333984375, forward time: 10.2364022731781, backward time: 23.700311422348022
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 0 done
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
step: 1
step in try: 1
load_mbs: 0.00028777122497558594, forward time: 9.77486777305603, backward time: 23.712490558624268
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 1 done
step: 2
step in try: 2
load_mbs: 0.0002319812774658203, forward time: 9.776134967803955, backward time: 23.713502645492554
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 2 done
step: 3
step in try: 3
load_mbs: 0.00025153160095214844, forward time: 9.772047996520996, backward time: 23.70572590827942
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 3 done
step: 4
step in try: 4
load_mbs: 0.00023674964904785156, forward time: 9.776100635528564, backward time: 23.710386991500854
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 4 done
step: 5
step in try: 5
load_mbs: 0.00024008750915527344, forward time: 9.777616739273071, backward time: 23.709776401519775
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 5 done
step: 6
step in try: 6
load_mbs: 0.0002257823944091797, forward time: 9.781275987625122, backward time: 23.712626934051514
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 6 done
step: 7
step in try: 7
load_mbs: 0.0002353191375732422, forward time: 9.77216362953186, backward time: 23.7056782245636
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 7 done
step: 8
step in try: 8
load_mbs: 0.0002257823944091797, forward time: 9.770711898803711, backward time: 23.69498038291931
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 8 done
step: 9
step in try: 9
load_mbs: 0.00023221969604492188, forward time: 9.770573377609253, backward time: 23.69333553314209
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 9 done
[2024-09-12 22:12:31,843] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-12 22:12:34,040] [INFO] [engine.py:935:train] Training done.
