[2024-09-13 01:52:29,506] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 6
[2024-09-13 01:52:33,236] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-11-1/mb8.json Launching profiler...
[2024-09-13 01:52:35,114] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 01:52:38,233] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 6, world_size 11, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 01:52:40,219] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 01:52:41,446] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 01:53:20,851] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 01:53:25,295] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 01:53:25,295] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 01:53:37,624] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 01:53:37,625] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 01:53:37,625] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 01:53:37,627] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 01:53:37,627] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 11 nodes latency
[2024-09-13 01:53:37,913] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 01:53:37,913] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 01:53:39,011] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.46:2222, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221', '172.21.0.47:2222']
[2024-09-13 01:53:39,011] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 01:53:40,995] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 01:53:44,153] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 01:53:44,153] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.46:2222
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 01:53:46,140] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 01:53:47,580] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 11)
min_nodes: 3, max_nodes: 11, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:27] with 1 devices
StageExecutionResult[28:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:23] with 1 devices
StageExecutionResult[24:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
[2024-09-13 01:53:54,271] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 01:53:54,272] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 45829 from master
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:7] with 1 devices
StageExecutionResult[8:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
[2024-09-13 01:53:55,425] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 01:53:55,425] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10]}
[2024-09-13 01:53:55,426] [INFO] [engine.py:739:initialize_distributed] init pg: rank 6, world_size: 11, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10]}
[2024-09-13 01:53:55,426] [INFO] [engine.py:755:initialize_distributed] Waiting for a port information...
[2024-09-13 01:53:55,426] [INFO] [engine.py:758:initialize_distributed] Received torch master: 172.21.0.42:2220.45829
[2024-09-13 01:53:55,618] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 01:53:55,619] [INFO] [engine.py:775:initialize_distributed] [rank: 6] Distributed initialization is done.
[2024-09-13 01:53:55,619] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,290] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,476] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,717] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,949] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-13 01:53:57,036] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.3nodes> pipelines (b: 36)
2 x <oobleck.PipelineTemplate.4nodes> pipelines (b: 46)
B: 128
dataloader: mbs 8
[2024-09-13 01:54:15,236] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 01:54:15,237] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.0006928443908691406, forward time: 11.545143842697144, backward time: 25.928940773010254
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 0 done
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
step: 1
step in try: 1
load_mbs: 0.0006973743438720703, forward time: 11.131768941879272, backward time: 25.944232940673828
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 1 done
step: 2
step in try: 2
load_mbs: 0.0006468296051025391, forward time: 11.128864765167236, backward time: 25.94271421432495
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 2 done
step: 3
step in try: 3
load_mbs: 0.0006670951843261719, forward time: 11.12740421295166, backward time: 25.939066171646118
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 3 done
step: 4
step in try: 4
load_mbs: 0.0006430149078369141, forward time: 11.128687620162964, backward time: 25.93855619430542
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 4 done
step: 5
step in try: 5
load_mbs: 0.0006353855133056641, forward time: 11.128047704696655, backward time: 25.942087173461914
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 5 done
step: 6
step in try: 6
load_mbs: 0.0006694793701171875, forward time: 11.129547595977783, backward time: 25.945725679397583
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 6 done
step: 7
step in try: 7
load_mbs: 0.0006744861602783203, forward time: 11.129719018936157, backward time: 25.943296432495117
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 7 done
step: 8
step in try: 8
load_mbs: 0.0006272792816162109, forward time: 11.126628637313843, backward time: 25.94099998474121
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 8 done
step: 9
step in try: 9
load_mbs: 0.0006308555603027344, forward time: 11.125513076782227, backward time: 25.94001603126526
load_mbs cnt: 46, forward cnt: 46, backward cnt: 46
training step: 9 done
[2024-09-13 02:11:18,929] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-13 02:11:19,369] [INFO] [engine.py:935:train] Training done.
