[2024-09-13 01:52:27,179] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-13 01:52:30,375] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-11-1/mb8.json Launching profiler...
[2024-09-13 01:52:32,335] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 01:52:35,638] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 11, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 01:52:37,854] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 01:52:39,036] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 01:53:19,771] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 01:53:25,206] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 01:53:25,206] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-13 01:53:31,532] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-13 01:53:37,038] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 01:53:37,541] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 01:53:37,541] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 01:53:37,541] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 01:53:37,542] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 01:53:37,542] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 11 nodes latency
[2024-09-13 01:53:37,832] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 01:53:37,832] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 01:53:39,003] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221', '172.21.0.47:2222']
[2024-09-13 01:53:39,004] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 01:53:40,908] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 01:53:43,990] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 01:53:43,990] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 01:53:45,884] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 01:53:47,172] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 11)
min_nodes: 3, max_nodes: 11, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:27] with 1 devices
StageExecutionResult[28:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:23] with 1 devices
StageExecutionResult[24:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:7] with 1 devices
StageExecutionResult[8:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
[2024-09-13 01:53:54,184] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 01:53:54,185] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10]}
[2024-09-13 01:53:54,185] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 11, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10]}
[2024-09-13 01:53:54,186] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 45829
[2024-09-13 01:53:54,187] [INFO] [agent.py:232:forward_worker_port] Received worker port: 45829 from worker. Forwarding it to master...
[2024-09-13 01:53:54,189] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 01:53:54,189] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 45829 from master
[2024-09-13 01:53:55,537] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 01:53:55,537] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-13 01:53:55,538] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,169] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,359] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,602] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 01:53:56,843] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-13 01:53:56,937] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.3nodes> pipelines (b: 36)
2 x <oobleck.PipelineTemplate.4nodes> pipelines (b: 46)
B: 128
dataloader: mbs 8
[2024-09-13 01:54:15,150] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 01:54:15,151] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.0277252197265625, forward time: 13.72934103012085, backward time: 34.87154293060303
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 0 done
[2024-09-13 01:55:13,702] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 58550.76
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-13 01:55:13,703] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 8.3803 GB | cache_allocated: 9.5547 GB | max_cache_allocated: 9.5547 GB
step: 1
step in try: 1
load_mbs: 0.022286415100097656, forward time: 13.274074077606201, backward time: 34.84367895126343
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 1 done
[2024-09-13 01:56:13,530] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 59828.23
[2024-09-13 01:56:13,531] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 2
step in try: 2
load_mbs: 0.028453826904296875, forward time: 13.277958631515503, backward time: 34.83529233932495
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 2 done
[2024-09-13 01:57:45,656] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 92126.20
[2024-09-13 01:57:45,657] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 3
step in try: 3
load_mbs: 0.014053583145141602, forward time: 13.267074823379517, backward time: 34.8345890045166
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 3 done
[2024-09-13 01:59:40,457] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 114802.19
[2024-09-13 01:59:40,459] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 4
step in try: 4
load_mbs: 0.021618127822875977, forward time: 13.269210577011108, backward time: 34.83636713027954
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 4 done
[2024-09-13 02:01:36,637] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 116180.91
[2024-09-13 02:01:36,639] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 5
step in try: 5
load_mbs: 0.025551557540893555, forward time: 13.275673866271973, backward time: 34.845903635025024
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 5 done
[2024-09-13 02:03:29,343] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 112706.11
[2024-09-13 02:03:29,345] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 6
step in try: 6
load_mbs: 0.025876283645629883, forward time: 13.276639699935913, backward time: 34.8502037525177
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 6 done
[2024-09-13 02:05:20,971] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 111628.59
[2024-09-13 02:05:20,973] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 7
step in try: 7
load_mbs: 0.024501562118530273, forward time: 13.273942708969116, backward time: 34.850868701934814
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 7 done
[2024-09-13 02:07:13,167] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 112197.07
[2024-09-13 02:07:13,169] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 8
step in try: 8
load_mbs: 0.02608466148376465, forward time: 13.273475408554077, backward time: 34.846606731414795
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 8 done
[2024-09-13 02:09:13,202] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 120035.83
[2024-09-13 02:09:13,203] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
step: 9
step in try: 9
load_mbs: 0.03522133827209473, forward time: 13.276238203048706, backward time: 34.84252047538757
load_mbs cnt: 36, forward cnt: 36, backward cnt: 36
training step: 9 done
[2024-09-13 02:11:16,346] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 123144.53
[2024-09-13 02:11:16,348] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 8.0790 GB | max_mem_allocated: 12.3865 GB | cache_allocated: 13.9629 GB | max_cache_allocated: 13.9629 GB
[2024-09-13 02:11:16,348] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-13 02:11:19,263] [INFO] [engine.py:935:train] Training done.
