[2024-09-13 02:11:52,438] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 2
[2024-09-13 02:11:55,828] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-10-1/mb8.json Launching profiler...
[2024-09-13 02:11:57,650] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:12:00,946] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 2, world_size 10, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:12:03,870] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 02:12:05,039] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 02:12:43,617] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 02:12:48,041] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 02:12:48,042] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 02:13:04,177] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 02:13:04,177] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 02:13:04,178] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 02:13:04,178] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 02:13:04,178] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 10 nodes latency
[2024-09-13 02:13:04,468] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 02:13:04,468] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 02:13:05,686] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2222, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221']
[2024-09-13 02:13:05,687] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 02:13:07,545] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:13:10,788] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 02:13:10,788] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2222
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:13:13,631] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 02:13:15,546] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 10)
min_nodes: 3, max_nodes: 10, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:24] with 1 devices
StageExecutionResult[25:29] with 1 devices
StageExecutionResult[30:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:29] with 1 devices
StageExecutionResult[30:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:27] with 1 devices
StageExecutionResult[28:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
[2024-09-13 02:13:20,518] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 02:13:20,520] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9]}
[2024-09-13 02:13:20,520] [INFO] [engine.py:739:initialize_distributed] init pg: rank 2, world_size: 10, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9]}
[2024-09-13 02:13:20,520] [INFO] [engine.py:755:initialize_distributed] Waiting for a port information...
[2024-09-13 02:13:20,797] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 02:13:20,798] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 39265 from master
[2024-09-13 02:13:20,798] [INFO] [engine.py:758:initialize_distributed] Received torch master: 172.21.0.42:2220.39265
[2024-09-13 02:13:20,812] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 02:13:20,813] [INFO] [engine.py:775:initialize_distributed] [rank: 2] Distributed initialization is done.
[2024-09-13 02:13:20,813] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:13:21,104] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:13:21,721] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-13 02:13:21,803] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 2 x <oobleck.PipelineTemplate.5nodes> pipelines (b: 64)
B: 128
dataloader: mbs 8
[2024-09-13 02:13:34,216] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 02:13:34,216] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0, forward time: 14.178438663482666, backward time: 36.034770250320435
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 0 done
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
step: 1
step in try: 1
load_mbs: 0, forward time: 13.74154806137085, backward time: 36.015724182128906
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 1 done
step: 2
step in try: 2
load_mbs: 0, forward time: 13.739863634109497, backward time: 36.014811277389526
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 2 done
step: 3
step in try: 3
load_mbs: 0, forward time: 13.738112688064575, backward time: 36.022444009780884
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 3 done
step: 4
step in try: 4
load_mbs: 0, forward time: 13.736320734024048, backward time: 36.01915431022644
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 4 done
step: 5
step in try: 5
load_mbs: 0, forward time: 13.737295866012573, backward time: 36.01903581619263
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 5 done
step: 6
step in try: 6
load_mbs: 0, forward time: 13.740926265716553, backward time: 36.03549075126648
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 6 done
step: 7
step in try: 7
load_mbs: 0, forward time: 13.740586757659912, backward time: 36.03053092956543
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 7 done
step: 8
step in try: 8
load_mbs: 0, forward time: 13.74040961265564, backward time: 36.02964448928833
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 8 done
step: 9
step in try: 9
load_mbs: 0, forward time: 13.739653587341309, backward time: 36.03627824783325
load_mbs cnt: 0, forward cnt: 64, backward cnt: 64
training step: 9 done
[2024-09-13 02:29:01,522] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-13 02:29:03,170] [INFO] [engine.py:935:train] Training done.
