[2024-09-12 20:08:24,039] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-12 20:08:27,193] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-15-1/mb16.json Launching profiler...
[2024-09-12 20:08:29,173] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 20:08:32,364] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 15, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 20:08:35,210] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 20:08:36,168] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 20:08:59,457] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 20:09:02,723] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 20:09:02,724] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-12 20:09:07,903] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-12 20:09:12,510] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 20:09:13,263] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 20:09:13,263] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 20:09:13,263] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 20:09:13,264] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 20:09:13,264] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 15 nodes latency
[2024-09-12 20:09:13,585] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 20:09:13,585] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 20:09:14,666] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221', '172.21.0.47:2222', '172.21.0.47:2223', '172.21.0.90:2220', '172.21.0.90:2221', '172.21.0.90:2222']
[2024-09-12 20:09:14,667] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 20:09:16,693] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 20:09:19,841] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 20:09:19,841] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 20:09:22,678] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 20:09:23,892] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 15)
min_nodes: 2, max_nodes: 15, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:15] with 1 devices
StageExecutionResult[16:17] with 1 devices
StageExecutionResult[18:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
StageExecutionResult[0:2] with 1 devices
StageExecutionResult[3:4] with 1 devices
StageExecutionResult[5:6] with 1 devices
StageExecutionResult[7:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
StageExecutionResult[0:2] with 1 devices
StageExecutionResult[3:4] with 1 devices
StageExecutionResult[5:6] with 1 devices
StageExecutionResult[7:8] with 1 devices
StageExecutionResult[9:10] with 1 devices
StageExecutionResult[11:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:17] with 1 devices
StageExecutionResult[18:19] with 1 devices
StageExecutionResult[20:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
StageExecutionResult[0:2] with 1 devices
StageExecutionResult[3:4] with 1 devices
StageExecutionResult[5:6] with 1 devices
StageExecutionResult[7:8] with 1 devices
StageExecutionResult[9:9] with 1 devices
StageExecutionResult[10:10] with 1 devices
StageExecutionResult[11:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:17] with 1 devices
StageExecutionResult[18:19] with 1 devices
StageExecutionResult[20:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
[2024-09-12 20:09:29,749] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 20:09:29,751] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11], '172.21.0.90:2220': [12], '172.21.0.90:2221': [13], '172.21.0.90:2222': [14]}
[2024-09-12 20:09:29,751] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 15, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11], '172.21.0.90:2220': [12], '172.21.0.90:2221': [13], '172.21.0.90:2222': [14]}
[2024-09-12 20:09:29,752] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 44233
[2024-09-12 20:09:29,752] [INFO] [agent.py:232:forward_worker_port] Received worker port: 44233 from worker. Forwarding it to master...
[2024-09-12 20:09:29,754] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 20:09:29,755] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 44233 from master
[2024-09-12 20:09:29,921] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 20:09:29,922] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-12 20:09:29,922] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 20:09:30,452] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 20:09:30,506] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4942E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:31,383] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:32,348] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4942E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:33,694] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:34,094] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 20:09:34,807] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:35,355] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4942E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:36,575] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:36,924] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -9.0909E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:38,251] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:38,561] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:39,750] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:40,126] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 20:09:40,811] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 20:09:47,337] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 6 x <oobleck.PipelineTemplate.2nodes> pipelines (b: 9)
1 x <oobleck.PipelineTemplate.3nodes> pipelines (b: 10)
B: 64
dataloader: mbs 16
[2024-09-12 20:10:04,512] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 20:10:04,512] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.013981342315673828, forward time: 6.023395299911499, backward time: 14.394450187683105
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 0 done
[2024-09-12 20:10:44,920] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 40407.23
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-12 20:10:44,922] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 9.5473 GB | cache_allocated: 11.3281 GB | max_cache_allocated: 11.3281 GB
step: 1
step in try: 1
load_mbs: 0.01287841796875, forward time: 5.581308841705322, backward time: 14.478066682815552
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 1 done
[2024-09-12 20:11:33,166] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 48244.82
[2024-09-12 20:11:33,168] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 2
step in try: 2
load_mbs: 0.01571798324584961, forward time: 5.592403173446655, backward time: 14.388219118118286
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 2 done
[2024-09-12 20:12:35,774] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62606.34
[2024-09-12 20:12:35,775] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 3
step in try: 3
load_mbs: 0.014680624008178711, forward time: 5.591327905654907, backward time: 14.392439603805542
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 3 done
[2024-09-12 20:13:45,215] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 69440.63
[2024-09-12 20:13:45,217] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 4
step in try: 4
load_mbs: 0.01500701904296875, forward time: 5.589127540588379, backward time: 14.387773036956787
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 4 done
[2024-09-12 20:14:48,568] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 63352.34
[2024-09-12 20:14:48,570] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 5
step in try: 5
load_mbs: 0.01599287986755371, forward time: 5.5883424282073975, backward time: 14.384727001190186
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 5 done
[2024-09-12 20:15:54,061] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 65491.69
[2024-09-12 20:15:54,063] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 6
step in try: 6
load_mbs: 0.015439033508300781, forward time: 5.586933135986328, backward time: 14.393105506896973
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 6 done
[2024-09-12 20:17:00,761] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 66699.20
[2024-09-12 20:17:00,762] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 7
step in try: 7
load_mbs: 0.012417793273925781, forward time: 5.578420639038086, backward time: 14.387648105621338
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 7 done
[2024-09-12 20:18:15,848] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 75086.59
[2024-09-12 20:18:15,849] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 8
step in try: 8
load_mbs: 0.013349771499633789, forward time: 5.594991207122803, backward time: 14.389586448669434
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 8 done
[2024-09-12 20:19:21,368] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 65519.95
[2024-09-12 20:19:21,370] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 9
step in try: 9
load_mbs: 0.012387514114379883, forward time: 5.592713832855225, backward time: 14.386443853378296
load_mbs cnt: 9, forward cnt: 9, backward cnt: 9
training step: 9 done
[2024-09-12 20:20:35,380] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 74010.62
[2024-09-12 20:20:35,381] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
[2024-09-12 20:20:35,381] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
