[2024-09-13 00:23:21,782] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-13 00:23:25,035] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-16-1/mb8.json Launching profiler...
[2024-09-13 00:23:26,887] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 00:23:30,010] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 16, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 00:23:31,970] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 00:23:33,191] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 00:24:12,703] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 00:24:16,559] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 00:24:16,559] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-13 00:24:22,894] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-13 00:24:28,560] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 00:24:29,287] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 00:24:29,288] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 00:24:29,288] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 00:24:29,289] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 00:24:29,289] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 16 nodes latency
[2024-09-13 00:24:29,649] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 00:24:29,650] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 00:24:30,742] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221', '172.21.0.47:2222', '172.21.0.47:2223', '172.21.0.90:2220', '172.21.0.90:2221', '172.21.0.90:2222', '172.21.0.90:2223']
[2024-09-13 00:24:30,743] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 00:24:32,779] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 00:24:35,983] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 00:24:35,983] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 00:24:37,909] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 00:24:39,709] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 16)
min_nodes: 3, max_nodes: 16, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:27] with 1 devices
StageExecutionResult[28:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:23] with 1 devices
StageExecutionResult[24:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:29] with 1 devices
StageExecutionResult[30:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:27] with 1 devices
StageExecutionResult[28:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:7] with 1 devices
StageExecutionResult[8:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[26:28] with 1 devices
StageExecutionResult[29:31] with 1 devices
StageExecutionResult[32:33] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:24] with 1 devices
StageExecutionResult[25:27] with 1 devices
StageExecutionResult[28:30] with 1 devices
StageExecutionResult[31:32] with 1 devices
StageExecutionResult[33:33] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:24] with 1 devices
StageExecutionResult[25:26] with 1 devices
StageExecutionResult[27:28] with 1 devices
StageExecutionResult[29:30] with 1 devices
StageExecutionResult[31:32] with 1 devices
StageExecutionResult[33:33] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:26] with 1 devices
StageExecutionResult[27:28] with 1 devices
StageExecutionResult[29:30] with 1 devices
StageExecutionResult[31:32] with 1 devices
StageExecutionResult[33:33] with 1 devices
StageExecutionResult[0:2] with 1 devices
StageExecutionResult[3:5] with 1 devices
StageExecutionResult[6:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:26] with 1 devices
StageExecutionResult[27:28] with 1 devices
StageExecutionResult[29:30] with 1 devices
StageExecutionResult[31:32] with 1 devices
StageExecutionResult[33:33] with 1 devices
StageExecutionResult[0:2] with 1 devices
StageExecutionResult[3:5] with 1 devices
StageExecutionResult[6:7] with 1 devices
StageExecutionResult[8:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:14] with 1 devices
StageExecutionResult[15:16] with 1 devices
StageExecutionResult[17:18] with 1 devices
StageExecutionResult[19:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:26] with 1 devices
StageExecutionResult[27:28] with 1 devices
StageExecutionResult[29:30] with 1 devices
StageExecutionResult[31:32] with 1 devices
StageExecutionResult[33:33] with 1 devices
[2024-09-13 00:24:58,843] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 00:24:58,844] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11], '172.21.0.90:2220': [12], '172.21.0.90:2221': [13], '172.21.0.90:2222': [14], '172.21.0.90:2223': [15]}
[2024-09-13 00:24:58,844] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 16, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9], '172.21.0.47:2222': [10], '172.21.0.47:2223': [11], '172.21.0.90:2220': [12], '172.21.0.90:2221': [13], '172.21.0.90:2222': [14], '172.21.0.90:2223': [15]}
[2024-09-13 00:24:58,844] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 38011
[2024-09-13 00:24:58,845] [INFO] [agent.py:232:forward_worker_port] Received worker port: 38011 from worker. Forwarding it to master...
[2024-09-13 00:24:58,848] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 00:24:58,849] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 38011 from master
[2024-09-13 00:24:58,965] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 00:24:58,966] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-13 00:24:58,966] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:24:59,308] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4942E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:24:59,689] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:24:59,919] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:00,182] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:00,376] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:00,953] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value 2.5059E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:01,475] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4942E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:01,826] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:02,148] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:02,501] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 00:25:08,135] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 4 x <oobleck.PipelineTemplate.4nodes> pipelines (b: 32)
B: 128
dataloader: mbs 8
[2024-09-13 00:25:23,864] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 00:25:23,865] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.029715776443481445, forward time: 9.297375202178955, backward time: 23.287585735321045
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 0 done
[2024-09-13 00:26:04,684] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 40815.70
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-13 00:26:04,686] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 7.5569 GB | cache_allocated: 8.9102 GB | max_cache_allocated: 8.9102 GB
step: 1
step in try: 1
load_mbs: 0.026279926300048828, forward time: 8.872555017471313, backward time: 23.273412466049194
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 1 done
[2024-09-13 00:26:42,785] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38097.45
[2024-09-13 00:26:42,787] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 2
step in try: 2
load_mbs: 0.029178619384765625, forward time: 8.873558759689331, backward time: 23.269896984100342
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 2 done
[2024-09-13 00:27:37,816] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 55026.56
[2024-09-13 00:27:37,817] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 3
step in try: 3
load_mbs: 0.025149822235107422, forward time: 8.87001371383667, backward time: 23.27004909515381
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 3 done
[2024-09-13 00:28:51,260] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 73439.99
[2024-09-13 00:28:51,262] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 4
step in try: 4
load_mbs: 0.022251605987548828, forward time: 8.867484331130981, backward time: 23.271246910095215
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 4 done
[2024-09-13 00:30:15,381] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 84115.12
[2024-09-13 00:30:15,383] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 5
step in try: 5
load_mbs: 0.032095909118652344, forward time: 8.875725030899048, backward time: 23.264408111572266
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 5 done
[2024-09-13 00:31:42,979] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 87593.52
[2024-09-13 00:31:42,981] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 6
step in try: 6
load_mbs: 0.025420427322387695, forward time: 8.872039079666138, backward time: 23.264248371124268
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 6 done
[2024-09-13 00:33:07,187] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 84204.30
[2024-09-13 00:33:07,189] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 7
step in try: 7
load_mbs: 0.022373199462890625, forward time: 8.864796161651611, backward time: 23.26798915863037
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 7 done
[2024-09-13 00:34:27,059] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 79868.38
[2024-09-13 00:34:27,060] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 8
step in try: 8
load_mbs: 0.0253446102142334, forward time: 8.870344161987305, backward time: 23.277497053146362
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 8 done
[2024-09-13 00:35:43,940] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 76877.81
[2024-09-13 00:35:43,943] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
step: 9
step in try: 9
load_mbs: 0.03000950813293457, forward time: 8.87613582611084, backward time: 23.276957273483276
load_mbs cnt: 32, forward cnt: 32, backward cnt: 32
training step: 9 done
[2024-09-13 00:37:03,301] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 79356.47
[2024-09-13 00:37:03,303] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 6.3175 GB | max_mem_allocated: 10.6838 GB | cache_allocated: 12.1309 GB | max_cache_allocated: 12.1309 GB
[2024-09-13 00:37:03,304] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-13 00:37:03,881] [INFO] [engine.py:935:train] Training done.
